default_context:
  project_name: 'fastapi-demo'
  project_slug: 'fastapi-demo'
  domain_main: 'fastapi-demo.com'
  domain_staging: 'stag.fastapi-demo.com'
  docker_swarm_stack_name_main: 'fastapi-demo-com'
  docker_swarm_stack_name_staging: 'stag-fastapi-demo-com'
  secret_key: '8861610eceb544c69098cb38c351e764'
  first_superuser: 'admin@fastapi-demo.com'
  first_superuser_password: '4dc2863ed5c24f4ebc410d28b5092d4c'
  backend_cors_origins: 'http://localhost, http://localhost:4200, http://localhost:3000, http://localhost:8080, https://localhost, https://localhost:4200, https://localhost:3000, https://localhost:8080, http://dev.fastapi-demo.com, https://stag.fastapi-demo.com, https://fastapi-demo.com, http://local.dockertoolbox.tiangolo.com, http://localhost.tiangolo.com'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@fastapi-demo.com'
  couchbase_user: 'admin'
  couchbase_password: '081eb822042145778267b30eea0438ab'
  couchbase_sync_gateway_cors: 'http://localhost:4984, http://localhost:4985, http://localhost, http://localhost:4200, http://localhost:3000, http://localhost:8080, http://dev.fastapi-demo.com, https://stag.fastapi-demo.com, https://db.stag.fastapi-demo.com, https://fastapi-demo.com, https://db.fastapi-demo.com, http://local.dockertoolbox.tiangolo.com, http://local.dockertoolbox.tiangolo.com:4984, http://localhost.tiangolo.com, http://localhost.tiangolo.com:4984'
  couchbase_sync_gateway_user: 'sync'
  couchbase_sync_gateway_password: '12e3d124c6bb42158667f830f123df15'
  traefik_constraint_tag: 'fastapi-demo.com'
  traefik_constraint_tag_staging: 'stag.fastapi-demo.com'
  traefik_public_network: 'traefik-public'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:4dc2863ed5c24f4ebc410d28b5092d4c'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  docker_image_sync_gateway: 'sync-gateway'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
